packages:
  - tools/*
  - packages/*
  - docs/*
  - playground/*
catalog:
  "@ls-lint/ls-lint": ^2.3.1
  "@nx/devkit": 23.1.0
  "@nx/eslint-plugin": 23.1.0
  "@nx/js": 23.1.0
  "@nx/plugin": 23.1.0
  "@nx/vite": 23.1.0
  "@nx/vitest": 23.1.0
  "@nx/workspace": 23.1.0
  "@power-plant/core": ^0.0.91
  "@power-plant/dtcg-schema": ^0.0.1
  "@power-plant/schema": ^0.0.89
  "@power-plant/utils": ^0.0.77
  "@powerlines/plugin-env": ^0.16.420
  "@powerlines/nx": ^0.13.251
  "@powerlines/plugin-untyped": ^0.2.627
  "@powerlines/tsconfig": ^0.4.255
  "@powerlines/tsdoc": ^0.2.203
  "@powerlines/plugin-tsdown": ^0.1.612
  "@shell-shock/eslint-plugin": ^0.0.88
  "@shell-shock/preset-cli": ^0.9.36
  "@shell-shock/core": ^0.17.24
  "@shell-shock/nx": ^0.0.97
  "@storm-software/config": ^1.138.70
  "@storm-software/config-tools": ^1.190.134
  "@storm-software/cspell": ^0.46.201
  "@storm-software/eslint-plugin-pnpm": ^0.0.97
  "@storm-software/eslint-config-react": ^0.0.91
  "@storm-software/eslint-plugin-tsdoc": ^0.0.97
  "@storm-software/git-tools": ^2.131.142
  "@storm-software/linting-tools": ^1.134.64
  "@storm-software/markdownlint": ^0.30.289
  "@storm-software/pnpm-tools": ^0.7.148
  "@storm-software/prettier": ^0.59.187
  "@storm-software/tsconfig": ^0.48.200
  "@storm-software/untyped": ^0.24.276
  "@storm-software/workspace-tools": ^1.297.3
  "@stryke/env": ^0.20.131
  "@stryke/fs": ^0.33.114
  "@stryke/hash": ^0.13.67
  "@stryke/helpers": ^0.10.52
  "@stryke/path": ^0.29.39
  "@stryke/string-format": ^0.17.54
  "@stryke/type-checks": ^0.6.45
  "@stryke/types": ^0.12.40
  "@stryke/url": ^0.4.64
  "@tailwindcss/node": ^4.3.3
  "@types/node": ^25.9.5
  "@typescript/native-preview": 7.0.0-dev.20251218.3
  c12: ^3.3.4
  chalk: ^5.6.2
  copyfiles: ^2.4.1
  defu: ^6.1.7
  eslint: ^10.9.0
  eslint-flat-config-utils: ^3.2.0
  fast-glob: ^3.3.3
  jiti: ^2.7.0
  json5: ^2.2.3
  jsonc-eslint-parser: ^3.3.0
  lefthook: ^2.1.10
  log4brains: ^1.1.0
  nx: 23.1.0
  pkg-types: ^2.3.1
  prettier: ^3.9.6
  rimraf: ^6.1.3
  shadcn: ^4.19.0
  smol-toml: ^1.8.0
  style-dictionary: ^5.5.2
  tailwindcss: ^4.3.3
  tsconfig-paths: ^4.2.0
  untyped: ^2.0.0
  verdaccio: 6.0.5
  vite: ^8.2.2
  vitest: ~4.1.11
  yaml: ^2.9.0
  zod: ^4.4.3
  zx: ^8.8.5
  powerlines: ^0.47.211
  "@storm-software/tsdoc": ^0.13.286
overrides:
  "@emnapi/core": 1.11.2
  "@emnapi/runtime": 1.11.2
  cookie: ">=0.7.0"
fetchTimeout: 240000
cleanupUnusedCatalogs: true
catalogMode: strict
linkWorkspacePackages: true
engineStrict: true
allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  core-js: true
  esbuild: true
  lefthook: true
  nx: true
  unrs-resolver: true
